In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
## Define the vocabulary size
voc_size=10000

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
# one hot representation 
one_hot_repr =[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[2432, 5188, 5742, 9395],
 [2432, 5188, 5742, 8502],
 [2432, 5721, 5742, 2387],
 [5072, 9156, 4310, 8339, 9367],
 [5072, 9156, 4310, 8339, 9863],
 [9286, 2432, 4795, 5742, 2456],
 [4382, 526, 7434, 8339]]

In [8]:
##  word embeding representation 

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np 
import pandas as pd

In [9]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2432 5188 5742 9395]
 [   0    0    0    0 2432 5188 5742 8502]
 [   0    0    0    0 2432 5721 5742 2387]
 [   0    0    0 5072 9156 4310 8339 9367]
 [   0    0    0 5072 9156 4310 8339 9863]
 [   0    0    0 9286 2432 4795 5742 2456]
 [   0    0    0    0 4382  526 7434 8339]]


In [10]:
# feature representation 
din = 10

In [11]:
model = Sequential()
model.add(Embedding(voc_size,din,input_length = sent_length))
model.compile('adam','mse')


2025-05-25 15:46:00.220437: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2
2025-05-25 15:46:00.220596: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2025-05-25 15:46:00.220824: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2025-05-25 15:46:00.221184: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-05-25 15:46:00.221648: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

2025-05-25 15:46:25.512848: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 320ms/step


array([[[ 2.91866921e-02, -7.44128227e-03,  4.64080609e-02,
          1.82434581e-02,  1.69377364e-02,  2.64386646e-02,
          4.18803804e-02,  3.68505605e-02, -1.07216947e-02,
         -2.32939720e-02],
        [ 2.91866921e-02, -7.44128227e-03,  4.64080609e-02,
          1.82434581e-02,  1.69377364e-02,  2.64386646e-02,
          4.18803804e-02,  3.68505605e-02, -1.07216947e-02,
         -2.32939720e-02],
        [ 2.91866921e-02, -7.44128227e-03,  4.64080609e-02,
          1.82434581e-02,  1.69377364e-02,  2.64386646e-02,
          4.18803804e-02,  3.68505605e-02, -1.07216947e-02,
         -2.32939720e-02],
        [ 2.91866921e-02, -7.44128227e-03,  4.64080609e-02,
          1.82434581e-02,  1.69377364e-02,  2.64386646e-02,
          4.18803804e-02,  3.68505605e-02, -1.07216947e-02,
         -2.32939720e-02],
        [-2.84867771e-02,  2.02379338e-02,  6.10620901e-03,
          2.18972452e-02,  8.90779495e-03,  2.99596786e-03,
         -4.86981869e-03, -9.31024551e-05,  4.706043

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2432, 5188, 5742, 9395], dtype=int32)

In [15]:
model.predict(embedded_docs[0])


1/1 [==============================] - 0s 128ms/step


array([[ 2.91866921e-02, -7.44128227e-03,  4.64080609e-02,
         1.82434581e-02,  1.69377364e-02,  2.64386646e-02,
         4.18803804e-02,  3.68505605e-02, -1.07216947e-02,
        -2.32939720e-02],
       [ 2.91866921e-02, -7.44128227e-03,  4.64080609e-02,
         1.82434581e-02,  1.69377364e-02,  2.64386646e-02,
         4.18803804e-02,  3.68505605e-02, -1.07216947e-02,
        -2.32939720e-02],
       [ 2.91866921e-02, -7.44128227e-03,  4.64080609e-02,
         1.82434581e-02,  1.69377364e-02,  2.64386646e-02,
         4.18803804e-02,  3.68505605e-02, -1.07216947e-02,
        -2.32939720e-02],
       [ 2.91866921e-02, -7.44128227e-03,  4.64080609e-02,
         1.82434581e-02,  1.69377364e-02,  2.64386646e-02,
         4.18803804e-02,  3.68505605e-02, -1.07216947e-02,
        -2.32939720e-02],
       [-2.84867771e-02,  2.02379338e-02,  6.10620901e-03,
         2.18972452e-02,  8.90779495e-03,  2.99596786e-03,
        -4.86981869e-03, -9.31024551e-05,  4.70604338e-02,
         4.